### ISSUE TITLE
Empty parameter passing to a build

### ISSUE THREAD

**Issue by alexkrytsky** [huserben/TfsExtensions#117]
Is there a way to pass an empty parameter to a Trigger Build Task?
the required format is key:val, key2:val2. Any possible way to make it something like key: , key2:val2 and in the triggered build, it would be just an empty parameter?

Right now just doing this and overriding some default values this way:
```yaml
variables:
  - name: MULTILINE_PARAM
    value: |
      PARAM1:somevar,
      PARAM2:secondparam,
      PATH:'',
      EMPTYPARAM:''
  - name: CUSTOM_PARAMS
    value: |
      PARAM1:overridevalue,
      PATH:\some\custom\path\here

steps:
  - template: templates/trigger_pipeline.yaml
    parameters:
      PIPELINE_PARAMS: "$(MULTILINE_PARAM),$(CUSTOM_PARAMS)"
```

In the trigger_pipeline.yaml I'm using the task and passing **PIPELINE_PARAMS** in **buildParameters**. But I need _EMPTYPARAM_ to remain empty when triggering a build.
