### ISSUE TITLE
Enhancement: Support YAML style buildParameters mapping

### ISSUE THREAD

**Issue by krispenner** [huserben/TfsExtensions#137]
It would be super awesome to support parameters like any other task/template would in YAML.

So instead of:
```yml
buildParameters: 'name1:value1,name2:value2'
```

It would be:
```yml
buildParameters:
  name1: value1
  name2: value2
```
