### ISSUE TITLE
Build parameters are being set as variables

### ISSUE THREAD

**Issue by pedrolamas** [huserben/TfsExtensions#142]
I have a pipeline where I'm using [template parameters](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#parameters), like on this example:

```yaml
parameters:
  - name: environment
    type: string
    displayName: Environment
    default: 'dev'
    values:
      - 'dev'
      - 'qa'
      - 'prod'

steps:
  - script: echo ${{ parameters.environment }}
```

If I manually trigger the above pipeline, I will get an option to specify the Environment parameter:

![image](https://user-images.githubusercontent.com/85504/84291305-d0f00600-ab3c-11ea-9aba-c9d757405813.png)

This is what it shows when I run the pipeline and select "qa" as environment:

![image](https://user-images.githubusercontent.com/85504/84291733-6a1f1c80-ab3d-11ea-9a70-bc34ca21c740.png)

So I assumed that the "buildParameters" would work with the above, so I wrote the task like this:

```yaml
- task: TriggerBuild@3
  displayName: Trigger e2e testing
  inputs:
    definitionIsInCurrentTeamProject: true
    buildDefinition: 'other-build'
    queueBuildForUserThatTriggeredBuild: true
    ignoreSslCertificateErrors: false
    useSameSourceVersion: false
    useSameBranch: false
    waitForQueuedBuildsToFinish: true
    waitForQueuedBuildsToFinishRefreshTime: '10'
    failTaskIfBuildsNotSuccessful: true
    cancelBuildsIfAnyFails: false
    treatPartiallySucceededBuildAsSuccessful: false
    downloadBuildArtifacts: false
    storeInEnvironmentVariable: false
    authenticationMethod: 'OAuth Token'
    password: '$(System.AccessToken)'
    enableBuildInQueueCondition: false
    dependentOnSuccessfulBuildCondition: false
    dependentOnFailedBuildCondition: false
    checkbuildsoncurrentbranch: false
    failTaskIfConditionsAreNotFulfilled: false
    buildParameters: 'environment: qa'
```

Problem is that from what I can see, all this does is create a variable called "environment" on the child pipeline, not actually passing a build parameter:

![image](https://user-images.githubusercontent.com/85504/84291782-786d3880-ab3d-11ea-9931-078bc1f907bd.png)

Am I missing something here?
