### ISSUE TITLE
Error message: Error: TF400813: The user '' is not authorized to access this resource.

### ISSUE THREAD

**Issue by christopherdalton** [huserben/TfsExtensions#157]
I appreciate that this may be an Azure DevOps issue not an issue with this task, but on the off chance the issue is already known I'm raisin this here too. I have raised this on MS Developer Forum but don't hold my breathe for a useful response.

Currently converting from Classic to YAML pipelines, using the 'Trigger Build' task in classic is fine, however when running in YAML pipeline the following permissions related issue occurs, I can confirm that permissions are correct as the task works as expected using non-YAML pipeline. Any guidance appreciated.

Current YAML;

```
## Build Components
- job: components
  dependsOn: reset

  pool:
    vmImage: 'ubuntu-latest'


  steps:
  - task: TriggerBuild@3
    displayName: 'Build: Engine'
    inputs:
      definitionIsInCurrentTeamProject: true
      buildDefinition: '15'
      queueBuildForUserThatTriggeredBuild: true
      ignoreSslCertificateErrors: false
      useSameSourceVersion: false
      useCustomSourceVersion: false
      useSameBranch: false
      branchToUse: 'refs/heads/dev'
      waitForQueuedBuildsToFinish: true
      waitForQueuedBuildsToFinishRefreshTime: '15'
      failTaskIfBuildsNotSuccessful: true
      cancelBuildsIfAnyFails: false
      treatPartiallySucceededBuildAsSuccessful: false
      downloadBuildArtifacts: true
      storeInEnvironmentVariable: true
      authenticationMethod: 'OAuth Token'
      enableBuildInQueueCondition: false
      dependentOnSuccessfulBuildCondition: false
      dependentOnFailedBuildCondition: false
      checkbuildsoncurrentbranch: false
      failTaskIfConditionsAreNotFulfilled: false
```

**Comment by christopherdalton** [comment]
After looking at some of the other issues raised, it's clear that `password: $(System.AccessToken)` is required. Documentation on using this field would be great!

**Comment by huserben** [comment]
Hi @christopherdalton 

Thanks for reporting this.

Yes it's on the todo list since quite a long time to properly document the yaml syntax, so far I simply never took the time to sit down and do it.

Sorry for the troubles but I'm glad you found the solution to the problem.

**Comment by KMoraz** [comment]
@huserben PR #139 addresses this issue. However [ADO marketplace](https://marketplace.visualstudio.com/items?itemName=benjhuser.tfs-extensions-build-tasks) refers to previous version (3.0.14, 3/21/2020).

**Comment by nguyenlamlll** [comment]
My "Trigger Build Task" version is 3.0.14. However, I still experience this issue.

When I use this YAML:
```
    - task: TriggerBuild@3
      inputs:
        definitionIsInCurrentTeamProject: true
        buildDefinition: '278'
        queueBuildForUserThatTriggeredBuild: true
        ignoreSslCertificateErrors: false
        useSameSourceVersion: true
        useSameBranch: true
        waitForQueuedBuildsToFinish: false
        storeInEnvironmentVariable: false
        authenticationMethod: 'OAuth Token'
        enableBuildInQueueCondition: false
        dependentOnSuccessfulBuildCondition: false
        dependentOnFailedBuildCondition: false
        checkbuildsoncurrentbranch: false
        failTaskIfConditionsAreNotFulfilled: false
```
The task fails and it throws an error `Error message: Error: TF400813: The user '' is not authorized to access this resource.
`.

I have to create the password variable. Then, the error goes away.
```
variables:
  password: $(System.AccessToken)

...

    - task: TriggerBuild@3
      inputs:
        definitionIsInCurrentTeamProject: true
        buildDefinition: '278'
        queueBuildForUserThatTriggeredBuild: true
        ignoreSslCertificateErrors: false
        useSameSourceVersion: true
        useSameBranch: true
        waitForQueuedBuildsToFinish: false
        storeInEnvironmentVariable: false
        authenticationMethod: 'OAuth Token'
        **password: '$(password)'**
        enableBuildInQueueCondition: false
        dependentOnSuccessfulBuildCondition: false
        dependentOnFailedBuildCondition: false
        checkbuildsoncurrentbranch: false
        failTaskIfConditionsAreNotFulfilled: false
```
