### ISSUE TITLE
Trouble using Build Parameters in triggered pipeline

### ISSUE THREAD

**Issue by Hoyzer90** [huserben/TfsExtensions#182]
Hi I'm trying to use the BuildParameters to pass a test suite name from PipelineA to B,
PipelineA trigger:
```
      task: TriggerBuild@3
      displayName: 'Trigger e2e test run'
      inputs:
        buildDefinition: 'app-e2e'
        useSameBranch: false
        branchToUse: UserStory/US12345
        waitForQueuedBuildsToFinish: true
        authenticationMethod: OAuth Token
        password: $(System.AccessToken)
        buildParameters: 'TestSuite: APP-API'```
```

This is part of the second pipeline where I'm trying to use the parameter
```
task: SoapUIProForAzureDevOpsTask@1
  displayName: 'SoapUI Pro for Azure DevOps'
  inputs:
    project: 'API-ReadyAPI'
    testSuite: $(TestSuite)
```

I can use $(TestSuite) to get the property thats passed between pipelines but then the problem is if I want to run the pipelineB on its own the testSuite input is set to "$(TestSuite)" instead of empty which causes it to not run any tests, if I use ${{TestSuite}} then when I run the e2e on its own it runs the full project as I want but when run as part of pipelineA its not set so it runs all tests instead of just the testSuite.

If I try setting TestSuite as an empty variable in pipelineB then pipelineAs value doesn't get used

Is there a way to use the parameter thats passed in only if its populated? Or another way of accessing the variable that will return empty if not found? I'm new to working with yaml so I don't know whats possible, any of the ways I've tried causes issues in either the standalone or the triggered pipeline
