### ISSUE TITLE
Waiting for triggered builds from different team-projects results in ##[error]Cannot read property 'definition' of null

### ISSUE THREAD

**Issue by BewotecDaVinci** [huserben/TfsExtensions#190]
Hi,

I really like the plugin but at the moment I am struggling to make it run for our needs.

Thats our setup: We start different builds from various teamprojects via the triggered build plugin and put all of them in the build queue. After that I would like to wait for each of those builds.

Unfortunately the wait-for-build-task tries to wait for **all** triggered builds on the **same** teamproject. This results in an error "##[error]Cannot read property 'definition' of null"

![grafik](https://user-images.githubusercontent.com/16084582/131121299-0f534c9a-6c4b-4f5b-9a6b-177d8885dc72.png)

Is there any possiblity to wait only for certain builds? Or wait for all of them within one wait-for-build-task, but in a way that the different teamprojects are considered right?

If not it would be great to have the possiblity to define a custom name for the triggered builds environment variable for the trigger-build-task and the wait-for-build-task. I would then have the chance to define different names for the various builds and wait for each.

Regards,
Michael

**Comment by BewotecDaVinci** [comment]
Hi,

thanks for the quick response. I gave the powershell solution a try and after some modifications it uses to work now. 

Cache triggered build id

```
  - task: PowerShell@2
    displayName: 'Caching triggered build id for ServiceA'
    inputs:
        targetType: 'inline'
        script: |
          Write-Host "Caching triggered build id"
          Write-Host "##vso[task.setvariable variable=ServiceABuildId;]$(TriggeredBuildIds)"
          Write-Host "Clearing triggered build id"
          Write-Host "##vso[task.setvariable variable=TriggeredBuildIds;]"
```

Restore triggered build id

```
- task: PowerShell@2
    displayName: 'Restoring triggered build id for ServiceA'
    inputs:
        targetType: 'inline'
        script: |
          Write-Host "Restoring triggered build id"
          Write-Host "##vso[task.setvariable variable=TriggeredBuildIds;]$($env:ServiceABuildId)"
```

Thanks for your help
