### ISSUE TITLE
TriggerBuild yaml pipeline - Passing parameter doesnt override default value

### ISSUE THREAD

**Issue by GitHubAre** [huserben/TfsExtensions#192]
Hello,

We use latest version 3.1.1 of the extension.
task `TriggerBuild@3`

I have a pipeline in YAML that triggers another one, this is in the **calling pipeline**
```
  - task: TriggerBuild@3
    displayName: 'Trigger SIPTEST pipeline'
    inputs:
      buildDefinition: 'siptest'
      useSameBranch: false
      branchToUse: master
      waitForQueuedBuildsToFinish: true
      authenticationMethod: 'OAuth Token'
      password: $(System.AccessToken)
      queueBuildForUserThatTriggeredBuild: true
      waitForQueuedBuildsToFinishRefreshTime: 15
      buildParameters: >
        mcugitsha: $(Build.SourceVersion),
        TriggeredBy: Triggered_by_$(Build.DefinitionName)/$(Build.BuildNumber)
```

another is also yaml pipeline, this one is **triggered** from above task:
parameters:
```
- name: mcugitsha
  type: string
  default: testwest

steps:
  - powershell: |
      Get-ChildItem -Path Env: | %{write-host "$($_.Name) = $($_.Value)"}
  - script: echo ${{parameters.mcugitsha}}
```

The "script" step prints always: **echo testwest**
Which is the default value.
Based on what I can see in this issue: https://github.com/huserben/TfsExtensions/issues/153
It should be possible to pass the parameter inside.
I can access the $(mcugitsha) variable, but its not the "prettiest" because its not explicitly declared.
I havent found real good example of this yaml syntax, therefore I might have used it incorrectly.

**Comment by huserben** [comment]
Hi @GitHubAre 

I quickly recreated your scenario and for me it works. I have a pipeline that defines two template parameters, one with free text and one with a defined set of accepted values:

``` yaml
parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - vs2017-win2016
  - ubuntu-latest
  - ubuntu-16.04
  - macOS-latest
  - macOS-10.14
- name: Test
  type: string
  default: Whatever

trigger: none

jobs:
- job: build
  displayName: build
  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.image }}
  
  - script: echo Test is ${{ parameters.Test }}
```

Then I triggered this with this command from another pipeline:

``` yaml
- task: TriggerBuild@3
  inputs:
    definitionIsInCurrentTeamProject: true
    buildDefinition: 'SomeGitRepo'
    queueBuildForUserThatTriggeredBuild: true
    ignoreSslCertificateErrors: false
    useSameSourceVersion: false
    useCustomSourceVersion: false
    useSameBranch: true
    waitForQueuedBuildsToFinish: false
    storeInEnvironmentVariable: false
    templateParameters: 'image: windows-latest, Test: TriggeredByBuild'
    authenticationMethod: 'OAuth Token'
    password: '$(System.AccessToken)'
    enableBuildInQueueCondition: false
    dependentOnSuccessfulBuildCondition: false
    dependentOnFailedBuildCondition: false
    checkbuildsoncurrentbranch: false
    failTaskIfConditionsAreNotFulfilled: false
```

This results in the build being triggered and correctly showing "TriggeredByBuild":
![image](https://user-images.githubusercontent.com/5486874/134920951-a7f02fd1-24f5-4a51-b636-00331a37289c.png)

Where does this leave us? My first hunch was - did you correctly specify the parameters as template parameters and not as "regular" variable? Do you spot anything that is different from my code above to yours that could make it not work for you? Did we exclude the obvious things, like some typo or so in the variable name?

**Comment by GitHubAre** [comment]
I have simplified my test even more and now I am just using the templateParameters:

```
steps:
  - task: TriggerBuild@3
    displayName: 'Trigger SIPTEST pipeline'
    inputs:
      buildDefinition: 'siptest'
      useSameBranch: false
      branchToUse: master
      waitForQueuedBuildsToFinish: true
      authenticationMethod: 'OAuth Token'
      password: $(System.AccessToken)
      queueBuildForUserThatTriggeredBuild: true
      waitForQueuedBuildsToFinishRefreshTime: 15
      templateParameters: 'mcugitsha: $(Build.SourceVersion)'
```

Output from the calling pipeline:

```
Context is Build - using Build Environment Variables
Build shall be triggered for same user that triggered current build: userxyz
Will trigger build with following template parameters: mcugitsha: 409dfdbe92f0d15e0ed77b4494af9590a0c4cc10
Found parameter mcugitsha with value: 409dfdbe92f0d15e0ed77b4494af9590a0c4cc10
Queued new Build for definition siptest: https://tfsurl.net/tfs/Playground/c87e4c70-d159-44bd-a79a-5643e7ea1adb/_build/results?buildId=1068
Will wait for queued build to be finished - Refresh time is set to 15 seconds
Following Builds will be awaited:
Build 1068 (siptest): https://tfsurl.net/tfs/Playground/c87e4c70-d159-44bd-a79a-5643e7ea1adb/_build/results?buildId=1068
Waiting for builds to finish - This might take a while...
```


But this still prints the default value:

```
parameters:
  - name: mcugitsha
    type: string
    default: testwest

trigger: none

steps:
  - powershell: |
      Get-ChildItem -Path Env: | %{write-host "$($_.Name) = $($_.Value)"}
  - script: echo ${{parameters.mcugitsha}}
```

We have on-premise server installation, maybe it doesnt work there and only in azure devops cloud.
I cant see any other explanation :(
