### ISSUE TITLE
Pass boolean buildParameter

### ISSUE THREAD

**Issue by ArianMoinianMicrosoft** [huserben/TfsExtensions#225]
Hello
How can I pass boolean buildParameter to the triggered build?
Best,
Arian

**Comment by huserben** [comment]
Hi @ArianMoinianMicrosoft 

what have you tried so far? Could you share a snippet of your pipeline (yaml or a screenshot if you use classic builds).

BuildParameters do not have a type if I remember correctly, so everything will be a string. Template Parameters can be typed, but in the task you still just send true/false and it should be converted automatically.

Hope that helps a bit - otherwise I'd need some more info about the specific use case.

**Comment by gherasim-learn** [comment]
Hello @huserben 
 The TriggerBuild@4 task is failing since 20 of March, it was working until 6 of March.
 From my investigations it is failing only if it use buildParameters
![image](https://user-images.githubusercontent.com/75733876/228460429-6137ed9b-b0a9-449a-9ff7-58def1a3076d.png)
This worked fine until 20 of March. Last successful run was on 6 of March.

**Comment by huserben** [comment]
@ArianMoinianMicrosoft 
Any update on this? As otherwise I'll close due to inactivity.

**Comment by avang-MT** [comment]
Hi @huserben,

I am having the same exact issue where the downstream template parameters are expecting a boolean parameter type. As a result of expecting a boolean parameter value, the upstream pipeline using the buildTrigger task fails.

Below is the upstream pipeline using the buildTrigger task and failing with template parameters:
![image](https://user-images.githubusercontent.com/101273809/231491527-985af65e-4eb9-4ec9-a226-9a83b849b848.png)

Below is the downstream template type parameters the downstream pipeline is expecting:
![image](https://user-images.githubusercontent.com/101273809/231491863-bc154176-a85d-4ac5-949a-093bf081c9f7.png)

As a result, I had to convert all boolean parameter types to string. And I could not use a list of predefined values for string type parameter seen at the bottom:
![image](https://user-images.githubusercontent.com/101273809/231492032-9ff72a70-bd6f-4ffd-adf4-d7d190a5f0cb.png)

Thanks in advance.

**Comment by huserben** [comment]
Hi @avang-MT 

to understand correctly. You only had to change the downstream pipeline template types (from boolean to string) and then the triggering worked, without any additional changes?

If so it might be a limitation by the API. Sadly it's not really documented how to use the template parameters, so it's hard for me to tell what could be wrong.

What _could_ help is if you could create a pipeline with a bool parameter and trigger it manually and capture the request that is sent (via the browser network tools). Perhaps we could reverse engineer if there is some specific thing sent if it's a bool value. However, if that would be the case, it would be tricky to handle this in the task, given that it's already quite messy now.

Anyway, if you could provide the request sent via manual triggering it's something to look at. Right now I'm short on time so I don't have any space to check this out in detail myself, so your support would be appreciated. Otherwise, I can try this myself, but you might have to way a bit longer.

Thanks!

**Comment by avang-MT** [comment]
> Hi @avang-MT
> 
> to understand correctly. You only had to change the downstream pipeline template types (from boolean to string) and then the triggering worked, without any additional changes?
> 
> If so it might be a limitation by the API. Sadly it's not really documented how to use the template parameters, so it's hard for me to tell what could be wrong.
> 
> What _could_ help is if you could create a pipeline with a bool parameter and trigger it manually and capture the request that is sent (via the browser network tools). Perhaps we could reverse engineer if there is some specific thing sent if it's a bool value. However, if that would be the case, it would be tricky to handle this in the task, given that it's already quite messy now.
> 
> Anyway, if you could provide the request sent via manual triggering it's something to look at. Right now I'm short on time so I don't have any space to check this out in detail myself, so your support would be appreciated. Otherwise, I can try this myself, but you might have to way a bit longer.
> 
> Thanks!

That's correct, in order for the downstream pipeline to be properly triggered I had to convert boolean types to string AND remove specified values accepted by the last parameter.

I'll manually test this in a development pipeline and let you know what I observe.

Updates to come. 

Thanks.

**Comment by avang-MT** [comment]
@huserben this is what I am seeing, templateParameters appears to convert the boolean into a string:

Template:
![image](https://user-images.githubusercontent.com/101273809/231857653-ded857df-b9fb-4790-8b27-5a1b53d5318f.png)

Payloads (True & False conditions):
![image](https://user-images.githubusercontent.com/101273809/231857552-2f3edf32-a865-4d47-af17-3828ce1294af.png)
![image](https://user-images.githubusercontent.com/101273809/231857839-f5c710bc-bfb7-49f2-9800-8bc7020446fe.png)

Is this a limitation by the API perhaps?

**Comment by iforapsy** [comment]
The current issue title is misworded as this discussion is about *template*Parameters and not *build*Parameters (aka queue time variables). huserben is correct that buildParameters don't seem to have a type: they are all strings.

Using Azure DevOps Server 2022.1 and `TriggerBuild@4`, I was able to trigger a build with a boolean template (aka runtime) parameter by passing the boolean value as all-lowercase and no quotes.

Here's the relevant excerpt from my working YAML pipeline definition. My pipeline triggers itself (i.e. it is recursive). `expandWildcards` is the boolean parameter.
```yaml
parameters:
- name: applicationList
  displayName: Names of applications to import (comma-separated). Wildcards supported.
  type: string
  default: '*'
- name: expandWildcards
  displayName: Expand wildcards in application names?
  type: boolean
  default: true

[...]
jobs:
- job: import
  steps:
  [...]
  - task: TriggerBuild@4
    displayName: Trigger this pipeline with expanded application list
    inputs:
      definitionIsInCurrentTeamProject: true
      buildDefinition: $(System.DefinitionId)
      # Misnomer: templateParameters is for runtime parameters
      templateParameters: >
        applicationList:$(applicationList),
        expandWildcards:false
      # Misnomer: buildParameters is for queue time variables
      buildParameters: >  # Propagate System.Debug and Agent.Diagnostic variables
        system.debug:$(System.Debug),
        agent.diagnostic:$(Agent.Diagnostic)
      authenticationMethod: 'OAuth Token'
      enableBuildInQueueCondition: false
      dependentOnSuccessfulBuildCondition: false
      dependentOnFailedBuildCondition: false
      checkbuildsoncurrentbranch: false
      failTaskIfConditionsAreNotFulfilled: false
[...]
```
Bonus: my excerpt shows how to pass in fake-boolean `buildParameters` as that's what `System.Debug` and `Agent.Diagnostic` are. Hope this helps someone.
