### ISSUE TITLE
TriggerBuild with array parameters

### ISSUE THREAD

**Issue by gherasim-learn** [huserben/TfsExtensions#226]
Hello!

I have a pipeline with a parameter of type object so I can define an array to loop through:
![image](https://user-images.githubusercontent.com/75733876/201304849-13abd9ff-b7f5-43f4-9f73-b477f2da5dc2.png)

I have a second pipeline that triggers the first pipeline. The issue is that I can't set a value for the template parameter databases:
![image](https://user-images.githubusercontent.com/75733876/201304513-243192a6-5761-4389-b3b5-509e7c154b2a.png)
The second pipeline fail with the following error 
![image](https://user-images.githubusercontent.com/75733876/201296572-6e8ef88b-e8c8-43f9-9e25-75063fa7b813.png)

**Comment by huserben** [comment]
Hi @gherasim-learn 

I've never used objects as inputs, so this was new to me. I've recreated a similar pipeline and tried to trigger it manually, specifying a custom input from the user.

```
trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: databases
    type: object
    displayName: Databases
    default:
      - first_database
      - second_database
      - third_database

steps:
- ${{ each database in parameters.databases }}:
  - script: echo ${{database}}
    displayName: 'Run a one-line script'

```

![Manual Trigger](https://user-images.githubusercontent.com/5486874/201388631-d0800303-6529-4935-bcf6-b390eb848c87.png)


This is what is sent from Azure to the backend:
![Request](https://user-images.githubusercontent.com/5486874/201388536-0177e26c-6dd1-4593-996e-e862d06bb132.png)

So I think you need a newline in the template parameter to work.

I tried to trigger it like this:
`templateParameters: 'databases: "- custom 1\n- Custom2"'`
But I got the same error as you did...

So far I'm not sure yet how this would work (if at all) - I'll keep you up to date when I find something out
