### ISSUE TITLE
Trigger only if no successful build exists for specified build definition and version

### ISSUE THREAD

**Issue by mankinskin** [huserben/TfsExtensions#262]
Hi, I would like to avoid triggering the other pipeline if it has already succeded with the current branch version (commit). Is this possible?

This is the task definition i am using:
```yaml
          - task: TriggerBuild@4
            displayName: Trigger Frontend Build Pipeline
            inputs:
              definitionIsInCurrentTeamProject: true
              buildDefinition: '30'
              queueBuildForUserThatTriggeredBuild: true
              ignoreSslCertificateErrors: false
              useSameSourceVersion: true
              useSameBranch: true
              waitForQueuedBuildsToFinish: true
              waitForQueuedBuildsToFinishRefreshTime: '60'
              failTaskIfBuildsNotSuccessful: true
              cancelBuildsIfAnyFails: true
              treatPartiallySucceededBuildAsSuccessful: false
              downloadBuildArtifacts: false
              storeInEnvironmentVariable: false
              authenticationMethod: 'OAuth Token'
              password: '$(System.AccessToken)'
              enableBuildInQueueCondition: true
              includeCurrentBuildDefinition: true
              dependentOnSuccessfulBuildCondition: true
              dependentBuildsList: '30'
              dependentOnFailedBuildCondition: false
              checkbuildsoncurrentbranch: true
              failTaskIfConditionsAreNotFulfilled: false
```
